services:
  - type: web
    name: taskmanager-backend
    runtime: node
    rootDir: task-manager-backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production